export const menus = [
  {
    title: 'useRequest',
    children: [
      { link: 'useRequest/doc/index' },
      { link: 'useRequest/doc/basic' },
      { link: 'useRequest/doc/loadingDelay' },
      { link: 'useRequest/doc/polling' },
      { link: 'useRequest/doc/ready' },
      { link: 'useRequest/doc/refreshDeps' },
      { link: 'useRequest/doc/refreshOnWindowFocus' },
      { link: 'useRequest/doc/debounce' },
      { link: 'useRequest/doc/throttle' },
      { link: 'useRequest/doc/cache' },
      { link: 'useRequest/doc/retry' },
    ],
  },
  // {
  //   title: 'Scene',
  //   children: [
  //     'useAntdTable',
  //     'useFusionTable',
  //     'useInfiniteScroll',
  //     'usePagination',
  //     'useDynamicList',
  //     'useVirtualList',
  //     'useHistoryTravel',
  //     'useNetwork',
  //     'useSelections',
  //     'useCountDown',
  //     'useCounter',
  //     'useTextSelection',
  //     'useWebSocket',
  //   ],
  // },
  // {
  //   title: 'LifeCycle',
  //   children: ['useMount', 'useUnmount', 'useUnmountedRef'],
  // },
  // {
  //   title: 'State',
  //   children: [
  //     'useSetState',
  //     'useBoolean',
  //     'useToggle',
  //     'use-url-state',
  //     'useCookieState',
  //     'useLocalStorageState',
  //     'useSessionStorageState',
  //     'useDebounce',
  //     'useThrottle',
  //     'useMap',
  //     'useSet',
  //     'usePrevious',
  //     'useRafState',
  //     'useSafeState',
  //     'useGetState',
  //     'useResetState',
  //   ],
  // },
  // {
  //   title: 'Effect',
  //   children: [
  //     'useUpdateEffect',
  //     'useUpdateLayoutEffect',
  //     'useAsyncEffect',
  //     'useDebounceEffect',
  //     'useDebounceFn',
  //     'useThrottleFn',
  //     'useThrottleEffect',
  //     'useDeepCompareEffect',
  //     'useDeepCompareLayoutEffect',
  //     'useInterval',
  //     'useRafInterval',
  //     'useTimeout',
  //     'useRafTimeout',
  //     'useLockFn',
  //     'useUpdate',
  //   ],
  // },
  // {
  //   title: 'Dom',
  //   children: [
  //     'useEventListener',
  //     'useClickAway',
  //     'useDocumentVisibility',
  //     'useDrop',
  //     'useEventTarget',
  //     'useExternal',
  //     'useTitle',
  //     'useFavicon',
  //     'useFullscreen',
  //     'useHover',
  //     'useMutationObserver',
  //     'useInViewport',
  //     'useKeyPress',
  //     'useLongPress',
  //     'useMouse',
  //     'useResponsive',
  //     'useScroll',
  //     'useSize',
  //     'useFocusWithin',
  //   ],
  // },
  // {
  //   title: 'Advanced',
  //   children: [
  //     'useControllableValue',
  //     'useCreation',
  //     'useEventEmitter',
  //     'useIsomorphicLayoutEffect',
  //     'useLatest',
  //     'useMemoizedFn',
  //     'useReactive',
  //   ],
  // },
  // {
  //   title: 'Dev',
  //   children: ['useTrackedEffect', 'useWhyDidYouUpdate'],
  // },
];
