export const menus = [
  {
    title: 'useRequest',
    children: [
      'useRequest/doc/index',
      'useRequest/doc/basic',
      'useRequest/doc/loadingDelay',
      'useRequest/doc/polling',
      'useRequest/doc/refreshOnWindowFocus',
      'useRequest/doc/debounce',
      'useRequest/doc/throttle',
      'useRequest/doc/retry',
      'useRequest/doc/refreshDeps',
      'useRequest/doc/cache',
    ],
  },
  {
    title: 'Scene',
    children: [
      'useAntdTable',
      'useFusionTable',
      'useInfiniteScroll',
      'usePagination',
      'useDynamicList',
      'useVirtualList',
      'useHistoryTravel',
      'useNetwork',
      'useSelections',
      'useCountDown',
      'useCounter',
      'useTextSelection',
      'useWebSocket',
    ],
  },
  {
    title: 'LifeCycle',
    children: ['useMount', 'useUnmount', 'useUnmountedRef'],
  },
  {
    title: 'State',
    children: [
      'useSetState',
      'useBoolean',
      'useToggle',
      'use-url-state',
      'useCookieState',
      'useLocalStorageState',
      'useSessionStorageState',
      'useDebounce',
      'useThrottle',
      'useMap',
      'useSet',
      'usePrevious',
      'useRafState',
      'useSafeState',
      'useGetState',
    ],
  },
  {
    title: 'Effect',
    children: [
      'useUpdateEffect',
      'useUpdateLayoutEffect',
      'useAsyncEffect',
      'useDebounceEffect',
      'useDebounceFn',
      'useThrottleFn',
      'useThrottleEffect',
      'useDeepCompareEffect',
      'useInterval',
      'useTimeout',
      'useLockFn',
      'useUpdate',
    ],
  },
  {
    title: 'Dom',
    children: [
      'useEventListener',
      'useClickAway',
      'useDocumentVisibility',
      'useDrop',
      'useEventTarget',
      'useExternal',
      'useTitle',
      'useFavicon',
      'useFullscreen',
      'useHover',
      'useInViewport',
      'useKeyPress',
      'useLongPress',
      'useMouse',
      'useResponsive',
      'useScroll',
      'useSize',
    ],
  },
  {
    title: 'Advanced',
    children: [
      'useControllableValue',
      'useCreation',
      'useEventEmitter',
      'useIsomorphicLayoutEffect',
      'useLatest',
      'useMemoizedFn',
      'useReactive',
    ],
  },
  {
    title: 'Dev',
    children: ['useTrackedEffect', 'useWhyDidYouUpdate'],
  },
];
